### ISSUE TITLE
foxy bug

### ISSUE THREAD

**Issue by simulacrus** [ros-visualization/rqt_publisher#27] opened 2021-04-23 11:29 UTC
I tested the foxy-devel branch and found that rqt_publisher doesn't responding to a change in a message. I think the problem is in [commit](https://github.com/ros-visualization/rqt_publisher/commit/67918b633fa7564e85006bacef9c5b7a660877e8#diff-e3c8f417cb661f1fc740294dfa10156526da16257d12ecc1dfee4d20788d7397) where `_change_publisher_expression` was deleted but https://github.com/ros-visualization/rqt_publisher/blob/foxy-devel/src/rqt_publisher/publisher.py#L158 doesn't change

**Comment by coalman321** [comment] 2021-05-26 13:54
Specifically it looks like this commit was the one that removed the change handler 367049ecc4ce3cabed9d5ca452fb478a98a3ba21
But this is definitely a bit of an issue, as it makes this plugin near useless.

**Comment by coalman321** [comment] 2021-05-26 14:37
I have now confirmed that reverting that specific commit fixes the issue. So the removed code was not in fact dead code... Ill open up a PR in a minute or so that fixes this against foxy-devel.

**Comment by ivanpauno** [comment] 2021-06-29 19:55
#28 fixed the issue, thanks @coalman321 !!

I've released the fixed version for foxy/galactic/rolling:

- https://github.com/ros/rosdistro/pull/30066
- https://github.com/ros/rosdistro/pull/30067
- https://github.com/ros/rosdistro/pull/30068

so the issue will be fixed in next patch release.

**Closed by ivanpauno** 2021-06-29 19:55 UTC
Labels: bug
